### ISSUE TITLE
AUTOMATIC1111 extension of PwW + ControlNet

### ISSUE THREAD

**Issue by lwchen6309** [cloneofsimo/paint-with-words-sd#34]
Hi @cloneofsimo, I just implemented PwW extension for AUTOMATIC1111 webui [here](https://github.com/lwchen6309/sd-controlnet-pww). (I haven't update any readme yet)

Now the issue is, my implementation combines PwW and ControlNet, which is based on the [controller extension](https://github.com/Mikubill/sd-webui-controlnet), thus making code much more complicated. 

I wonder shall we just import all the repo of PwW+ControlNet as submodule here, or just leave it as another independent repo. What do you say?

For UI of PwW+ControlNet, please see the following example:

![screencapture-127-0-0-1-7860-2023-03-13-10_56_34](https://user-images.githubusercontent.com/42672685/224598103-01d6f37d-10e0-4e61-972c-90187047881b.png)

**Comment by cloneofsimo** [comment]
Hey @lwchen6309, thank you for your work. I think either of the choices are all good, adding it as a submodule here would direct people to your repo when they come by, but adding your repo to the readme would be just as good as well.
Since you are making all the progress here, I think you have the full right to decide what to do here (such as adding donation links to yourself, etc)
Thank you for your works again!

**Comment by lwchen6309** [comment]
I see, let it be a submodule then :)
